import type { NextConfig } from 'next'
import generatedRedirects from './data/redirects.generated.json' with { type: 'json' }

// Typed explicitly because an empty generated file widens to `never[]`.
const redirects = generatedRedirects as { source: string; destination: string }[]

const nextConfig: NextConfig = {
  reactStrictMode: true,
  trailingSlash: false,
  poweredByHeader: false,

  images: {
    formats: ['image/avif', 'image/webp'],
    // Trimmed to the breakpoints the design actually uses — fewer variants
    // means a better CDN cache hit rate.
    deviceSizes: [640, 768, 1024, 1280, 1536, 1920],
    imageSizes: [96, 160, 256, 384],
    minimumCacheTTL: 31536000,
  },

  // Generated by velite's prepare() from each article's `redirectFrom`, so
  // re-categorising an article never produces a 404.
  async redirects() {
    return redirects.map((r) => ({ ...r, permanent: true }))
  },

  async headers() {
    return [
      {
        source: '/:path*',
        headers: [
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
          {
            key: 'Strict-Transport-Security',
            value: 'max-age=63072000; includeSubDomains; preload',
          },
        ],
      },
      {
        source: '/search-index.json',
        headers: [{ key: 'Cache-Control', value: 'public, max-age=0, must-revalidate' }],
      },
    ]
  },
}

export default nextConfig
